name: riverpod_freezed
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  freezed: ^2.5.7

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
